python3 -m run --ginc configs/co3d.gin --scene_name 290_30780_59102 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 349_36520_66801 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 12_109_707 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 423_58951_114401 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 412_56309_109304 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 236_24789_51101 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 373_41487_82902 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 386_46018_91908 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 374_41919_83809 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 402_52411_102607 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 197_21206_41908 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 47_2694_7604 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 430_60724_119000 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 399_51048_100100 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 396_49638_97805 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 399_51079_100203 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 414_56915_110208 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 395_49190_97202 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 163_17880_33208 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 397_50080_98510 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 396_49564_97706 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 416_57463_111200 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 386_46212_92202 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 117_13756_28310 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 374_41996_84006 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 411_56010_108204 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 391_46910_93404 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 399_50932_99902 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 424_59119_114602 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 58_3355_10203 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 153_16983_31803 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 262_28099_53708 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 378_44212_88104 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 395_49194_97208 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 385_45782_91506 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 386_45955_91804 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 380_44942_90000 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 31_1375_4208 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 216_22866_49900 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 385_45373_90905 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 372_41093_82000 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 70_5758_13307 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 40_1899_5810 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 366_39368_76707 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 397_49988_98402 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 106_12689_26708 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 396_49566_97710 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 351_37059_67904 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 165_18081_34406 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
python3 -m run --ginc configs/co3d.gin --scene_name 28_967_2810 --ginb run.run_train=False  --ginb run.run_eval=False --ginb run.run_render=True --ginb load_co3d_data.render_scene_interp=True
