dataset_type: tanks_and_temples
model: plenoxel_torch
batching: all_images

N_rand: 4096
max_steps: 200000

i_print: 100
i_validation: 50000
use_pixel_centers: true

no_ndc: true
chunk: 16384

upsamp_every: 50000
reso: "[[128, 128, 128], [256, 256, 256], [512, 512, 512], [640, 640, 640]]"
background_nlayers: 64
background_reso: 1024
lr_sigma: 3.0e+1
lr_sh: 1.0e-2
lr_sigma_delay_steps: 15000
thresh_type: "weight"
lambda_tv": 5.0e-5
lambda_tv_sh": 5.0e-3
lambda_tv_background_sigma": 1.0e-3
lambda_tv_background_color: 1.0e-3
lambda_beta: 1.0e-5
lambda_sparsity: 1.0e-11
background_brightness: 1.0
tv_early_only: 0